protected/modules/feedback/models/FeedBack.php
<?php
/**
 * FeedBack основная модель
 *
 * @category YupeController
 * @package  yupe.modules.feedback.models
 * @author   YupeTeam <team@yupe.ru>
 * @license  BSD http://ru.wikipedia.org/wiki/%D0%9B%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F_BSD
 * @link     http://yupe.ru
 *
 **/
use yupe\widgets\YPurifier;

/**
 * This is the model class for table "{{FeedBack}}".
 *
 * The followings are the available columns in table '{{FeedBack}}':
 * @property integer $id
 * @property string $create_time
 * @property string $update_time
 * @property string $name
 * @property string $email
 * @property string $theme
 * @property string $text
 * @property integer $type
 * @property integer $status
 * @property integer $ip
 * @property integer $category_id
 * @property string $phone
 * @property integer $is_faq
 */
class FeedBack extends yupe\models\YModel
{

    /**
     *
     */
    const STATUS_NEW = 0;
    /**
     *
     */
    const STATUS_PROCESS = 1;
    /**
     *
     */
    const STATUS_FINISHED = 2;
    /**
     *
     */
    const STATUS_ANSWER_SENDED = 3;

    /**
     *
     */
    const TYPE_DEFAULT = 0;

    /**
     *
     */
    const IS_FAQ_NO = 0;
    /**
     *
     */
    const IS_FAQ = 1;

    /**
     * Returns the static model of the specified AR class.
     * @param  string $className
     * @return FeedBack the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{feedback_feedback}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return [
            ['name, email, theme, text', 'required'],
            ['name, email, theme, text, phone', 'filter', 'filter' => [$obj = new YPurifier(), 'purify']],
            ['type, status, answer_user, is_faq, type, category_id', 'numerical', 'integerOnly' => true],
            ['is_faq', 'in', 'range' => array_keys($this->getIsFaqList())],
            ['status', 'in', 'range' => array_keys($this->getStatusList())],
            ['type', 'in', 'range' => array_keys($this->getTypeList())],
            ['name, email, phone', 'length', 'max' => 150],
            ['theme', 'length', 'max' => 250],
            ['ip', 'length', 'max' => 20],
            ['answer_time', 'length', 'max' => 100],
            ['email', 'email'],
            ['answer', 'filter', 'filter' => 'trim'],
            [
                'id, create_time, update_time, name, email, theme, text, type, status, ip',
                'safe',
                'on' => 'search',
            ],
        ];
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('FeedbackModule.feedback', 'ID'),
            'create_time' => Yii::t('FeedbackModule.feedback', 'Created'),
            'update_time' => Yii::t('FeedbackModule.feedback', 'Updated'),
            'name' => Yii::t('FeedbackModule.feedback', 'Name'),
            'email' => Yii::t('FeedbackModule.feedback', 'Email'),
            'phone' => Yii::t('FeedbackModule.feedback', 'Phone'),
            'theme' => Yii::t('FeedbackModule.feedback', 'Topic'),
            'text' => Yii::t('FeedbackModule.feedback', 'Text'),
            'type' => Yii::t('FeedbackModule.feedback', 'Type'),
            'answer' => Yii::t('FeedbackModule.feedback', 'Reply'),
            'answer_time' => Yii::t('FeedbackModule.feedback', 'Reply time'),
            'answer_user' => Yii::t('FeedbackModule.feedback', 'Replied'),
            'is_faq' => Yii::t('FeedbackModule.feedback', 'In FAQ'),
            'status' => Yii::t('FeedbackModule.feedback', 'Status'),
            'ip' => Yii::t('FeedbackModule.feedback', 'Ip-address'),
            'category_id' => Yii::t('FeedbackModule.feedback', 'Category'),
        ];
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        $criteria = new CDbCriteria();

        $criteria->compare('id', $this->id);

        if (!empty($this->create_time)) {
            $criteria->addBetweenCondition(
                'create_time',
                $this->create_time.' 00:00:00',
                $this->create_time.' 23:59:59',
                'AND'
            );
        }

        $criteria->compare('update_time', $this->update_time, true);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('email', $this->email, true);
        $criteria->compare('theme', $this->theme, true);
        $criteria->compare('text', $this->text, true);
        $criteria->compare('type', $this->type);
        $criteria->compare('status', $this->status);
        $criteria->compare('ip', $this->ip);
        $criteria->compare('is_faq', $this->is_faq);
        $criteria->compare('category_id', $this->category_id);

        return new CActiveDataProvider(get_class($this), [
            'criteria' => $criteria,
            'sort' => ['defaultOrder' => 'create_time DESC, status ASC'],
        ]);
    }

    /**
     * Обновляем дату изменения. Если новая запись
     * обновляем необходимые поля:
     *
     * @return void
     */
    public function beforeValidate()
    {
        $this->update_time = new CDbExpression('NOW()');

        if ($this->isNewRecord) {
            $this->create_time = $this->update_time;
            $this->ip = Yii::app()->getRequest()->userHostAddress;

            if (!$this->type) {
                $this->type = self::TYPE_DEFAULT;
            }
        }

        return parent::beforeValidate();
    }

    /**
     * Именованные условия:
     *
     * @return array
     */
    public function scopes()
    {
        return [
            'new' => [
                'condition' => 'status = :status',
                'params' => [':status' => self::STATUS_NEW],
            ],
            'answered' => [
                'condition' => 'status = :status',
                'params' => [':status' => self::STATUS_ANSWER_SENDED],
            ],
            'faq' => [
                'condition' => 'is_faq = :is_faq',
                'params' => [':is_faq' => self::IS_FAQ],
            ],
        ];
    }

    /**
     * Имя пользователя который ответил:
     *
     * @return string
     */
    public function getAnsweredUser()
    {
        return $this->answer_user ? User::model()->findByPk($this->answer_user) : Yii::t(
            'FeedbackModule.feedback',
            '-'
        );
    }

    /**
     * Список возможных статусов:
     *
     * @return array
     */
    public function getStatusList()
    {
        return [
            self::STATUS_NEW => Yii::t('FeedbackModule.feedback', 'New message'),
            self::STATUS_PROCESS => Yii::t('FeedbackModule.feedback', 'Message in handle'),
            self::STATUS_FINISHED => Yii::t('FeedbackModule.feedback', 'Message was handled'),
            self::STATUS_ANSWER_SENDED => Yii::t('FeedbackModule.feedback', 'Reply was received'),
        ];
    }

    /**
     * Получаем текстовый статус:
     *
     * @return string
     */
    public function getStatus()
    {
        $data = $this->getStatusList();

        return isset($data[$this->status]) ? $data[$this->status] : Yii::t(
            'FeedbackModule.feedback',
            'Unknown status message'
        );
    }

    /**
     * Список возможных типов:
     *
     * @return array
     */
    public function getTypeList()
    {
        $types = Yii::app()->getModule('feedback')->types;

        if ($types) {
            $types[self::TYPE_DEFAULT] = Yii::t('FeedbackModule.feedback', 'Default');
        } else {
            $types = [self::TYPE_DEFAULT => Yii::t('FeedbackModule.feedback', 'Default')];
        }

        return $types;
    }

    /**
     * Получаем тип:
     *
     * @return string
     */
    public function getType()
    {
        $data = $this->getTypeList();

        return isset($data[$this->type]) ? $data[$this->type] : Yii::t(
            'FeedbackModule.feedback',
            'Unknown message type'
        );
    }

    /**
     * Массив текстовых статусов:
     *
     * @return array
     */
    public function getIsFaqList()
    {
        return [
            self::IS_FAQ_NO => Yii::t('FeedbackModule.feedback', 'No'),
            self::IS_FAQ => Yii::t('FeedbackModule.feedback', 'Yes'),
        ];
    }

    /**
     * Получаем класс по статусу:
     *
     * @return string label-class
     */
    public function getStatusClass()
    {
        return $this->status
            ? (
            ($this->status == self::STATUS_NEW)
                ? 'warning'
                : (
            ($this->status == self::STATUS_ANSWER_SENDED)
                ? 'success'
                : 'default'
            )
            )
            : 'info';
    }

    /**
     * Получаем текст, при необходимости обрезаем:
     *
     * @param mixed $size - максимальная длина
     *
     * @return string
     */
    public function getText($size = false)
    {
        if (false === $size || $size > mb_strlen($this->text)) {
            return $this->text;
        }

        $p = new CHtmlPurifier();

        return $p->purify(
            mb_substr($this->text, 0, $size).'...'
        );
    }

    /**
     * Находится ли ответ в FAQ:
     *
     * @return string
     */
    public function getIsFaq()
    {
        $data = $this->getIsFaqList();

        return isset($data[$this->is_faq]) ? $data[$this->is_faq] : Yii::t('FeedbackModule.feedback', '*unknown*');
    }

    /**
     * Связи:
     *
     * @return array
     */
    public function relations()
    {
        return [

protected/modules/feedback/views/feedbackBackend/_form.php
<?php
$form = $this->beginWidget(
    'bootstrap.widgets.TbActiveForm',
    [
        'id'                     => 'feedback-form',
        'enableAjaxValidation'   => false,
        'enableClientValidation' => true,
        'type'                   => 'vertical',
        'action'                 => $model->isNewRecord ? ['create'] : ['update', 'id' => $model->id],
        'htmlOptions'            => ['class' => 'well'],
    ]
); ?>
<div class="alert alert-info">
    <?=  Yii::t('FeedbackModule.feedback', 'Fields with'); ?>
    <span class="required">*</span>
    <?=  Yii::t('FeedbackModule.feedback', 'are required.'); ?>
</div>

<?=  $form->errorSummary($model); ?>

<div class="row">
    <div class="col-sm-2">
        <?=  $form->dropDownListGroup(
            $model,
            'type',
            [
                'widgetOptions' => [
                    'data'        => Yii::app()->getModule('feedback')->getTypes(),
                    'htmlOptions' => [
                        'empty' => Yii::t('FeedbackModule.feedback', '--choose--'),
                    ],
                ],
            ]
        ); ?>
    </div>
    <div class="col-sm-3">
        <?=  $form->dropDownListGroup(
            $model,
            'category_id',
            [
                'widgetOptions' => [
                    'data'        => Yii::app()->getComponent('categoriesRepository')->getFormattedList(
                            (int)Yii::app()->getModule('feedback')->mainCategory
                        ),
                    'htmlOptions' => [
                        'empty' => Yii::t('FeedbackModule.feedback', '--choose--'),
                    ],
                ],
            ]
        ); ?>
    </div>
    <div class="col-sm-2">
        <?=  $form->dropDownListGroup(
            $model,
            'status',
            [
                'widgetOptions' => [
                    'data'        => $model->getStatusList(),
                    'htmlOptions' => [
                        'empty' => Yii::t('FeedbackModule.feedback', '--choose--'),
                    ],
                ],
            ]
        ); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-7">
        <?=  $form->textFieldGroup($model, 'name'); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-7">
        <?=  $form->textFieldGroup($model, 'email'); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-7">
        <?=  $form->textFieldGroup($model, 'phone'); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-7">
        <?=  $form->textFieldGroup($model, 'theme'); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 form-group">
        <?=  $form->labelEx($model, 'text'); ?>
        <?php $this->widget(
            $this->module->getVisualEditor(),
            [
                'id'        => substr(md5(microtime()), 0, 7),
                'model'     => $model,
                'attribute' => 'text',
            ]
        ); ?>
        <?=  $form->error($model, 'text'); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 form-group">
        <?=  $form->labelEx($model, 'answer'); ?>
        <?php $this->widget(
            $this->module->getVisualEditor(),
            [
                'id'        => substr(md5(microtime()), 0, 7),
                'model'     => $model,
                'attribute' => 'answer',
            ]
        ); ?>
        <?=  $form->error($model, 'answer'); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-7">
        <?=  $form->checkBoxGroup($model, 'is_faq'); ?>
    </div>
</div>
<?php if ($model->status == FeedBack::STATUS_ANSWER_SENDED && isset($model->answer_user)): ?>
    <div class="row">
        <div class="col-sm-7 form-group">
            <label><?=  Yii::t('FeedbackModule.feedback', 'Ответил'); ?> <?=  CHtml::link(
                    $model->getAnsweredUser()->nick_name,
                    ['/user/userBackend/view', 'id' => $model->answer_user]
                ); ?> (<?=  $model->answer_time; ?>)</label>
            <?=  $model->answer; ?>
        </div>
    </div>
<?php endif; ?>

<div class='controls'>
    <?php $this->widget(
        'bootstrap.widgets.TbButton',
        [
            'buttonType' => 'submit',
            'context'    => 'primary',
            'label'      => $model->isNewRecord ? Yii::t(
                    'FeedbackModule.feedback',
                    'Create message and continue'
                ) : Yii::t('FeedbackModule.feedback', 'Save message and continue'),
        ]
    ); ?>

    <?php $this->widget(
        'bootstrap.widgets.TbButton',
        [
            'buttonType'  => 'submit',
            'htmlOptions' => ['name' => 'submit-type', 'value' => 'index'],
            'label'       => $model->isNewRecord ? Yii::t(
                    'FeedbackModule.feedback',
                    'Create message and close'
                ) : Yii::t('FeedbackModule.feedback', 'Save message and close'),
        ]
    ); ?>
</div>

<?php $this->endWidget(); ?>

protected/modules/feedback/views/feedbackBackend/_search.php
<?php
$form = $this->beginWidget(
    'bootstrap.widgets.TbActiveForm',
    [
        'action'      => Yii::app()->createUrl($this->route),
        'method'      => 'get',
        'type'        => 'vertical',
        'htmlOptions' => [
            'class' => 'well',
        ],
    ]
); ?>

<div class="row">
    <div class="col-sm-3">
        <?=  $form->textFieldGroup($model, 'name'); ?>
    </div>
    <div class="col-sm-3">
        <?=  $form->textFieldGroup($model, 'email'); ?>
    </div>
    <div class="col-sm-3">
        <?=  $form->textFieldGroup($model, 'phone'); ?>
    </div>
    <div class="col-sm-3">
        <?=  $form->textFieldGroup($model, 'theme'); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-3">
        <?=  $form->dropDownListGroup(
            $model,
            'type',
            [
                'widgetOptions' => [
                    'data'        => $model->getTypeList(),
                    'htmlOptions' => [
                        'empty' => '---',
                    ],
                ],
            ]
        ); ?>
    </div>
    <div class="col-sm-3">
        <?=  $form->dropDownListGroup(
            $model,
            'status',
            [
                'widgetOptions' => [
                    'data'        => $model->getStatusList(),
                    'htmlOptions' => [
                        'empty' => '---',
                    ],
                ],
            ]
        ); ?>
    </div>
    <div class="col-sm-3">
        <?=  $form->dropDownListGroup(
            $model,
            'category_id',
            [
                'widgetOptions' => [
                    'data'        => Yii::app()->getComponent('categoriesRepository')->getFormattedList(
                            (int)Yii::app()->getModule('feedback')->mainCategory
                        ),
                    'htmlOptions' => [
                        'empty' => '---',
                    ],
                ],
            ]
        ); ?>
    </div>
    <div class="col-sm-3">
        <?=  $form->datePickerGroup(
            $model,
            'create_time',
            [
                'widgetOptions' => [
                    'options' => [
                        'format'    => 'yyyy-mm-dd',
                        'weekStart' => 1,
                        'autoclose' => true,
                    ],
                ],
                'prepend'       => '<i class="fa fa-calendar"></i>',
            ]
        ); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-7">
        <?=  $form->checkBoxGroup($model, 'is_faq', $model->isFaqList); ?>
    </div>
</div>
<div class='row hidden'>
    <div class="col-sm-12">
        <?php $this->widget(
            'application.modules.yupe.widgets.editors.imperaviRedactor.ImperaviRedactorWidget',
            [
                'model'     => $model,
                'attribute' => 'answer',
            ]
        ); ?>
    </div>
</div>

<?php $this->widget(
    'bootstrap.widgets.TbButton',
    [
        'context'     => 'primary',
        'encodeLabel' => false,
        'buttonType'  => 'submit',
        'label'       => '<i class="fa fa-search">&nbsp;</i>' . Yii::t(
                'FeedbackModule.feedback',
                'Find messages '
            ),
    ]
); ?>

<?php $this->endWidget(); ?>

protected/modules/feedback/views/feedbackBackend/answer.php
<?php

$this->breadcrumbs = [
    Yii::t('FeedbackModule.feedback', 'Messages ') => ['/feedback/feedbackBackend/index'],
    $model->theme => ['/feedback/feedbackBackend/view', 'id' => $model->id],
    Yii::t('FeedbackModule.feedback', 'Reply'),
];

$this->pageTitle = Yii::t('FeedbackModule.feedback', 'Messages - answer');

$this->menu = [
    [
        'icon' => 'fa fa-fw fa-list-alt',
        'label' => Yii::t('FeedbackModule.feedback', 'Messages management'),
        'url' => ['/feedback/feedbackBackend/index']
    ],
    [
        'icon' => 'fa fa-fw fa-plus-square',
        'label' => Yii::t('FeedbackModule.feedback', 'Create message '),
        'url' => ['/feedback/feedbackBackend/create']
    ],
    [
        'label' => Yii::t('FeedbackModule.feedback', 'Reference value') . ' «' . mb_substr(
                $model->theme,
                0,
                32
            ) . '»'
    ],
    [
        'icon' => 'fa fa-fw fa-pencil',
        'label' => Yii::t('FeedbackModule.feedback', 'Edit message '),
        'url' => [
            '/feedback/feedbackBackend/update',
            'id' => $model->id
        ]
    ],
    [
        'icon' => 'fa fa-fw fa-eye',
        'label' => Yii::t('FeedbackModule.feedback', 'View message'),
        'url' => [
            '/feedback/feedbackBackend/view',
            'id' => $model->id
        ]
    ],
    [
        'icon' => 'fa fa-fw fa-envelope',
        'label' => Yii::t('FeedbackModule.feedback', 'Reply for message'),
        'url' => [
            '/feedback/feedbackBackend/answer',
            'id' => $model->id
        ]
    ],
    [
        'icon' => 'fa fa-fw fa-trash-o',
        'label' => Yii::t('FeedbackModule.feedback', 'Remove message '),
        'url' => '#',
        'linkOptions' => [
            'submit' => ['/feedback/feedbackBackend/delete', 'id' => $model->id],
            'params' => [Yii::app()->getRequest()->csrfTokenName => Yii::app()->getRequest()->csrfToken],
            'confirm' => Yii::t('FeedbackModule.feedback', 'Do you really want to remove message?'),
        ]
    ],
];
?>

<script type='text/javascript'>
    $(document).ready(function () {
        var email = '<?=  $model->email; ?>';
        $('input:submit').click(function () {
            if (window.confirm('<?=  Yii::t('FeedbackModule.feedback', 'Reply will be send on '); ?>' + email + '<?=  Yii::t('FeedbackModule.feedback', ' продолжить ?'); ?>'))
                return true;
            return false;
        });
    });
</script>

<div class="page-header">
    <h1>
        <?=  Yii::t('FeedbackModule.feedback', 'Reply on message'); ?><br/>
        <small>&laquo;<?=  $model->theme; ?>&raquo;</small>
    </h1>
</div>

<?php $this->widget(
    'bootstrap.widgets.TbDetailView',
    [
        'data' => $model,
        'attributes' => [
            'create_time',
            'name',
            'email',
            'phone',
            'theme',
            [
                'name' => 'text',
                'type' => 'raw',
            ],
            [
                'name' => 'type',
                'value' => $model->getType(),
            ],
            [
                'name' => 'status',
                'value' => $model->getStatus(),
            ],
        ],
    ]
); ?>

<br/><br/>

<?php
$form = $this->beginWidget(
    'bootstrap.widgets.TbActiveForm',
    [
        'id' => 'feed-back-form-answer',
        'action' => ['/feedback/feedbackBackend/answer', 'id' => $model->id],
        'enableAjaxValidation' => false,
        'enableClientValidation' => true,
        'type' => 'vertical',
        'htmlOptions' => ['class' => 'well'],
    ]
); ?>
<div class="alert alert-info">
    <?=  Yii::t('FeedbackModule.feedback', 'Fields with'); ?>
    <span class="required">*</span>
    <?=  Yii::t('FeedbackModule.feedback', 'are required.'); ?>
</div>

<?=  $form->errorSummary($answerForm); ?>

<div class="row">
    <div class="col-sm-12 form-group">
        <?=  $form->labelEx($answerForm, 'answer'); ?>
        <?php $this->widget(
            $this->module->getVisualEditor(),
            [
                'model' => $answerForm,
                'attribute' => 'answer',
                'options' => [
                    'imageUpload' => Yii::app()->baseUrl . '/index.php/yupe/backend/AjaxImageUpload/',
                ],
                'htmlOptions' => ['rows' => 20, 'cols' => 6],
            ]
        ); ?>
        <?=  $form->error($answerForm, 'answer'); ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <?=  $form->checkBoxGroup($answerForm, 'is_faq'); ?>
    </div>
</div>

<?php $this->widget(
    'bootstrap.widgets.TbButton',
    [
        'buttonType' => 'submit',
        'context' => 'primary',
        'label' => Yii::t('FeedbackModule.feedback', 'Send reply for message'),
    ]
); ?>

<?php $this->endWidget(); ?>

protected/modules/feedback/views/feedbackBackend/answerEmail.php
<html>
<head>
    <title><?=  Yii::t(
            'FeedbackModule.feedback',
            'Reply on message {site}',
            ['{site}' => Yii::app()->name]
        ); ?></title>
</head>
<body>
<?=  Yii::t('FeedbackModule.feedback', 'Reply on message {site}', ['{site}' => Yii::app()->name]); ?>
<br/><br/>

<?=  Yii::t('FeedbackModule.feedback', 'You wrote'); ?> : <?=  CHtml::encode($model->theme); ?><br/><br/>
<?=  CHtml::encode($model->text); ?><br/><br/>

<?=  Yii::t('FeedbackModule.feedback', 'Our Reply'); ?>: <?=  $model->answer; ?><br/><br/>

<br/>
<?=  Yii::t(
    'FeedbackModule.feedback',
    'Truly yours {site} administration!',
    ['{site}' => CHtml::encode(Yii::app()->name)]
); ?>
</body>
</html>

protected/modules/feedback/views/feedbackBackend/create.php
<?php
$this->breadcrumbs = [
    Yii::t('FeedbackModule.feedback', 'Messages ') => ['/feedback/feedbackBackend/index'],
    Yii::t('FeedbackModule.feedback', 'Creating'),
];

$this->pageTitle = Yii::t('FeedbackModule.feedback', 'Messages - add');

$this->menu = [
    [
        'icon'  => 'fa fa-fw fa-list-alt',
        'label' => Yii::t('FeedbackModule.feedback', 'Messages management'),
        'url'   => ['/feedback/feedbackBackend/index']
    ],
    [
        'icon'  => 'fa fa-fw fa-plus-square',
        'label' => Yii::t('FeedbackModule.feedback', 'Create message '),
        'url'   => ['/feedback/feedbackBackend/create']
    ],
];
?>
<h1>
    <?=  Yii::t('FeedbackModule.feedback', 'Messages '); ?>
    <small><?=  Yii::t('FeedbackModule.feedback', 'adding'); ?></small>
</h1>

<?=  $this->renderPartial('_form', ['model' => $model]); ?>

protected/modules/feedback/views/feedbackBackend/update.php
<?php
$this->breadcrumbs = [
    Yii::t('FeedbackModule.feedback', 'Messages ') => ['/feedback/feedbackBackend/index'],
    $model->theme                                  => ['/feedback/feedbackBackend/view', 'id' => $model->id],
    Yii::t('FeedbackModule.feedback', 'Edit'),
];

$this->pageTitle = Yii::t('FeedbackModule.feedback', 'Messages - edit');

$this->menu = [
    [
        'icon'  => 'fa fa-fw fa-list-alt',
        'label' => Yii::t('FeedbackModule.feedback', 'Messages management'),
        'url'   => ['/feedback/feedbackBackend/index']
    ],
    [
        'icon'  => 'fa fa-fw fa-plus-square',
        'label' => Yii::t('FeedbackModule.feedback', 'Create message '),
        'url'   => ['/feedback/feedbackBackend/create']
    ],
    [
        'label' => Yii::t('FeedbackModule.feedback', 'Reference value') . ' «' . mb_substr(
                $model->theme,
                0,
                32
            ) . '»'
    ],
    [
        'icon'  => 'fa fa-fw fa-pencil',
        'label' => Yii::t('FeedbackModule.feedback', 'Edit message '),
        'url'   => [
            '/feedback/feedbackBackend/update',
            'id' => $model->id
        ]
    ],
    [
        'icon'  => 'fa fa-fw fa-eye',
        'label' => Yii::t('FeedbackModule.feedback', 'View message'),
        'url'   => [
            '/feedback/feedbackBackend/view',
            'id' => $model->id
        ]
    ],
    [
        'icon'  => 'fa fa-fw fa-envelope',
        'label' => Yii::t('FeedbackModule.feedback', 'Reply for message'),
        'url'   => [
            '/feedback/feedbackBackend/answer',
            'id' => $model->id
        ]
    ],
    [
        'icon'        => 'fa fa-fw fa-trash-o',
        'label'       => Yii::t('FeedbackModule.feedback', 'Remove message '),
        'url'         => '#',
        'linkOptions' => [
            'submit'  => ['/feedback/feedbackBackend/delete', 'id' => $model->id],
            'params'  => [Yii::app()->getRequest()->csrfTokenName => Yii::app()->getRequest()->csrfToken],
            'confirm' => Yii::t('FeedbackModule.feedback', 'Do you really want to remove message?'),
        ]
    ],
];
?>
<div class="page-header">
    <h1>
        <?=  Yii::t('FeedbackModule.feedback', 'Change message '); ?><br/>
        <small>&laquo;<?=  $model->theme; ?>&raquo;</small>
    </h1>
</div>

<?=  $this->renderPartial('_form', ['model' => $model]); ?>